exports.USERNAME_DOES_NOT_EXIST = 'USERNAME_DOES_NOT_EXIST';

exports.INCORRECT_PASSWORD = 'INCORRECT_PASSWORD';

exports.PERMISSION_DENIED = 'PERMISSION_DENIED';

// Unknown ErrorCodes
exports.UNKNOWN_ERROR = 'UNKNOWN_ERROR';